_target_: src.models.networks.warp.litmodule.WarpLitModule

net:
  _target_: src.models.networks.warp.sparse_conv_unet.SparseConvUNetToCLIP
  _partial_: true

  backbone_cfg:
    in_channels: ${data.in_channel}
    enc_channels: [16, 32, 48, 64, 80, 96, 112, 128]
    dec_channels: [16, 32, 48, 64, 80, 96, 112, 128]
    num_blocks: 2

  # last mlp
  adapter_cfg:
    in_channel: ${model.net.backbone_cfg.dec_channels[0]}
    text_channel: ${model.clip_encoder.text_dim}
    num_layers: 2
    last_norm: true

eval_cfg:
  eval_clip_text_alignment: false
  eval_clip_image_alignment: false
  ignore_background: false
  ignore_class_prob: false

  seg_eval:
    normalize_input: ${model.loss_cfg.seg_loss.normalize_input}
    text_clip_path: ${model.loss_cfg.seg_loss.text_clip_path}

use_prompt: false

compile: false
