repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1024']

-   repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
    -   id: curlylint
        types: [html]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [html, css]
        args: [--print-width=120, --single-quote]
