_target_: src.models.networks.openscene.litmodule.OpenSceneLitModule

net:
  _target_: src.models.networks.openscene.mink_unet.MinkUNet18A
  _partial_: true
  in_channels: ${data.in_channel}
  out_channels: ${model.clip_encoder.text_dim}

eval_cfg:
  eval_clip_text_alignment: false
  eval_clip_image_alignment: false

  seg_eval:
    normalize_input: ${model.loss_cfg.seg_loss.normalize_input}
    text_clip_path: ${model.loss_cfg.seg_loss.text_clip_path}

use_prompt: true

compile: false
