defaults:
  - opensegment3d_spunet34c

net:
  backbone:
    out_channels: ${model.clip_encoder.text_dim}

  hlevels: [4]
  backbone_ckpt: results/mosaic3d-spunet34c/checkpoints/epoch_159-step_0048000.ckpt
  decoder_ckpt: null
  freeze_backbone: true
