defaults:
  - openscene-lseg_openvocab

optimizer:
  _target_: src.models.optimization.build_optimizer
  _partial_: true
  optim_cfg:
    LR: 4e-3
    SCHEDULER: adam_onecycle
    OPTIMIZER: adam_onecycle
    WEIGHT_DECAY: 0.0001
    MOMENTUM: 0.9
    STEP_EPOCH: 50
    MULTIPLIER: 0.1
    CLIP_GRAD: False
    PCT_START: 0.39
    DIV_FACTOR: 1
    MOMS: [0.95, 0.85]

scheduler:
  _target_: src.models.optimization.build_scheduler
  _partial_: true
  last_epoch: -1
  optim_cfg: ${model.optimizer.optim_cfg}

clip_encoder:
  model_id: hf-hub:UCSC-VLAA/ViT-L-16-HTxt-Recap-CLIP
  text_dim: 768
