defaults:
  - ov3d_openvocab

net:
  _target_: src.models.networks.openscene.spconv_unet_v1m1_base.SpUNetBase
  _partial_: true

  in_channels: 6
  out_channels: 512
  channels: [32, 64, 128, 256, 128, 128, 96, 96] # MinkUNet18A (OpenScene default)
  layers: [2, 2, 2, 2, 2, 2, 2, 2] # MinkUNet18A (OpenScene default)
