_target_: src.models.networks.warp.litmodule.WarpLitModule

optimizer:
  _target_: src.models.optimization.build_optimizer
  _partial_: true
  optim_cfg:
    LR: 1e-3
    SCHEDULER: adam_onecycle
    OPTIMIZER: adam_onecycle
    WEIGHT_DECAY: 0.0001
    MOMENTUM: 0.9
    STEP_EPOCH: 50
    MULTIPLIER: 0.1
    PCT_START: 0.39
    DIV_FACTOR: 1
    MOMS: [0.95, 0.85]

scheduler:
  _target_: src.models.optimization.build_scheduler
  _partial_: true
  last_epoch: -1
  optim_cfg: ${model.optimizer.optim_cfg}

scheduler_interval: step

net:
  _target_: src.models.networks.warp.point_transformer_v3.PointTransformerV3ToCLIP
  _partial_: true

  voxel_size: 0.02

  backbone_cfg:
    in_channels: 6
    out_channels: 192
    enc_depths: [2, 2, 2, 6, 2]
    enc_channels: [32, 64, 128, 256, 512]
    enc_num_head: [2, 4, 8, 16, 32]
    enc_patch_size: [1024, 1024, 1024, 1024, 1024]
    dec_depths: [2, 2, 2, 2]
    dec_channels: [64, 64, 128, 256]
    dec_num_head: [4, 4, 8, 16]
    dec_patch_size: [1024, 1024, 1024, 1024]
    mlp_ratio: 4
    drop_path: 0.2
    out_code_backend: "unique"
    rand_perm_patch: true

  # last mlp
  adapter_cfg:
    in_channel: ${model.net.backbone_cfg.out_channels}
    text_channel: 512
    last_norm: true
    normalize_output: true

loss_cfg:
  caption_loss:
    reduction: weighted_sum
    use_logit_scale: true
  seg_loss:
    eval_only: true # no seg loss training if set to true
    normalize_input: false
    text_clip_path: /datasets/regionplc/text_embed/scannet_clip-ViT-B16_id.pth
    loss_type: cross_entropy
    ignore_label: ${data.train_dataset.ignore_label}
    learnable_logit: false
  binary_loss: false
  caption_loss_weight: 1.0
  seg_loss_weight: 1.0
  sync_dist: true # print synced loss (0.82 it/s vs 84 it/s)

# compile model for faster training with pytorch 2.0
clip_encoder:
  model_id: ViT-B/16
  text_dim: 512

compile: false

tags: ["point_transformer_v3"]
