_target_: src.models.lightning_modules.pointwise_contrastive_module.PointwiseContrastiveLanguageLitModule

net:
  _target_: src.models.networks.spunet.spconv_unet_v1m1_base.SpUNetBase
  _partial_: true
  in_channels: ${data.in_channel}
  out_channels: ${model.clip_encoder.text_dim} # 1152 for SigLIP, 768 for Recap
  base_channels: 32
  channels: [32, 64, 128, 256, 256, 128, 96, 96]
  layers: [2, 3, 4, 6, 2, 2, 2, 2]

loss_cfg:
  caption_loss:
    use_logit_scale: true

eval_cfg:
  ignore_background: false # Passed to ValidationEvaluator indirectly via dataset info
  ignore_class_prob: false # Likely not used in this module's validation logic

use_prompt: true
compile: false
