_target_: src.models.networks.regionplc.litmodule.RegionPLCLitModule

net:
  _target_: src.models.networks.ppt.model.PPT
  _partial_: true

  conditions: ${data.train_dataset.conditions}
  context_channels: 256
  backbone:
    _target_: src.models.networks.regionplc.sparse_convnet.SparseConvUNetTextSeg
    _partial_: true

    backbone_cfg:
      in_channel: ${data.in_channel}
      mid_channel: 16
      block_reps: 2
      block_residual: true
      custom_sp1x1: true
      num_blocks: 7
      pdnorm_bn: true
      pdnorm_decouple: true
      pdnorm_adaptive: true
      pdnorm_affine: true
      pdnorm_conditions: ${data.train_dataset.conditions}
      zero_init: true

    adapter_cfg:
      in_channel: ${model.net.backbone.backbone_cfg.mid_channel}
      text_channel: ${model.clip_encoder.text_dim}
      num_layers: 2
      last_norm: false

    binary_head_cfg: false # disable binary head

eval_cfg:
  eval_clip_text_alignment: false
  eval_clip_image_alignment: false
  ignore_background: false
  ignore_class_prob: false

  seg_eval:
    normalize_input: ${model.loss_cfg.seg_loss.normalize_input}
    text_clip_path: ${model.loss_cfg.seg_loss.text_clip_path}

use_prompt: true

# compile model for faster training with pytorch 2.0
compile: false
