_target_: src.models.networks.regionplc.litmodule.RegionPLCLitModule

optimizer:
  _target_: src.models.optimization.build_optimizer
  _partial_: true
  optim_cfg:
    LR: 4e-3
    SCHEDULER: adam_onecycle
    OPTIMIZER: adam_onecycle
    WEIGHT_DECAY: 0.0001
    MOMENTUM: 0.9
    STEP_EPOCH: 50
    MULTIPLIER: 0.1
    CLIP_GRAD: False
    PCT_START: 0.39
    DIV_FACTOR: 1
    MOMS: [0.95, 0.85]

scheduler:
  _target_: src.models.optimization.build_scheduler
  _partial_: true
  last_epoch: -1
  optim_cfg: ${model.optimizer.optim_cfg}

scheduler_interval: step

net:
  _target_: src.models.networks.ppt.model.PPT
  _partial_: true

  conditions: ${data.train_dataset.conditions}
  context_channels: 256
  backbone:
    _target_: src.models.networks.regionplc.sparse_convnet.SparseConvUNetTextSeg
    _partial_: true

    backbone_cfg:
      in_channel: ${data.in_channel}
      mid_channel: 16
      block_reps: 2
      block_residual: true
      custom_sp1x1: true
      num_blocks: 7
      pdnorm_bn: true
      pdnorm_decouple: true
      pdnorm_adaptive: true
      pdnorm_affine: true
      pdnorm_conditions: ${data.train_dataset.conditions}
      zero_init: true

    adapter_cfg:
      in_channel: ${model.net.backbone.backbone_cfg.mid_channel}
      text_channel: ${model.clip_encoder.text_dim}
      num_layers: 2
      last_norm: true

    binary_head_cfg: false # disable binary head

loss_cfg:
  caption_loss:
    reduction: weighted_sum
    use_logit_scale: true
  seg_loss:
    normalize_input: false
    text_clip_path: !!null
    loss_type: cross_entropy
    ignore_label: ${data.train_dataset.ignore_label}
    learnable_logit: false
    eval_only: true
  binary_loss: false
  caption_loss_weight: 1.0
  sync_dist: true

clip_encoder:
  model_id: ViT-B/16
  text_dim: 512

# compile model for faster training with pytorch 2.0
compile: false

eval_cfg:
  eval_clip_text_alignment: false
  eval_clip_image_alignment: false

  seg_eval:
    normalize_input: ${model.loss_cfg.seg_loss.normalize_input}
    text_clip_path: ${model.loss_cfg.seg_loss.text_clip_path}

use_prompt: false
