_target_: src.models.networks.warp.litmodule.WarpLitModule

net:
  _target_: src.models.networks.warp.mink_unet.MinkUNetToCLIP
  _partial_: true

  voxel_size: 0.02

  backbone_cfg:
    in_channels: 6
    out_channels: 192
    # MinkUNet18
    planes: [32, 64, 128, 256, 256, 192, 192, 192]
    layers: [2, 2, 2, 2, 2, 2, 2, 2]
    init_dim: 32
    voxel_size: ${model.net.voxel_size}

  # last mlp
  adapter_cfg:
    in_channel: ${model.net.backbone_cfg.out_channels}
    text_channel: 512
    last_norm: true
    normalize_output: true

compile: false
