# @package logger
wandb:
  _target_: src.utils.auto_resume_wandb_logger.AutoResumeWandbLogger
  name: null # name of the run. SLURM_JOB_ID when null
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "mosaic3d"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: []
  job_type: ""
