# @package model
optimizer:
  _target_: src.models.optimization.build_optimizer
  _partial_: true
  lr: 4e-3
  optim_cfg:
    LR: ${model.optimizer.lr}
    SCHEDULER: adam_onecycle
    OPTIMIZER: adam_onecycle
    WEIGHT_DECAY: 0.0001
    MOMENTUM: 0.9
    STEP_EPOCH: 50
    MULTIPLIER: 0.1
    CLIP_GRAD: False
    PCT_START: 0.39
    DIV_FACTOR: 1
    MOMS: [0.95, 0.85]

