# @package model.net
_target_: src.models.networks.warp.model.WarpModel
_partial_: true

voxel_size: 0.02

backbone:
  _target_: warpconvnet.models.backbones.mink_unet.MinkUNetBase
  in_channels: ${data.in_channel}
  out_channels: ${model.clip_encoder.text_dim}
  # MinkUNet18A
  planes: [32, 64, 128, 256, 128, 128, 96, 96]
  layers: [2, 2, 2, 2, 2, 2, 2, 2]
  init_dim: 32
  block_types: "bbbbbbbb"
