# @package model.net
_target_: src.models.networks.warp.model.WarpModel
_partial_: true

voxel_size: 0.02

backbone:
  _target_: warpconvnet.models.internal.backbones.voxel_transformer.VoxelTransformer
  in_channels: ${data.in_channel}
  out_channels: ${model.clip_encoder.text_dim}
  kernel_size: 3
  enc_channels: [32, 64, 128, 256, 512]
  enc_window_size: [32, 32, 32, 32, 32]
  enc_depths: [2, 2, 2, 6, 2]
  enc_num_head: [2, 4, 8, 16, 32]
  dec_channels: [256, 256, 256, 256]
  dec_window_size: [32, 32, 32, 32]
  dec_depths: [2, 2, 2, 2]
  dec_num_head: [4, 4, 8, 16]
  orders:
    - zero
    - xy
    - xz
    - yz
    - xyz
  shuffle_orders: true
  use_rope: true
  rope_base: null
  enc_rope_bases: [2000, 2000, 2000, 2000, 2000]
  dec_rope_bases: [2000, 2000, 2000, 2000]
  rope_learnable_theta: false
  mlp_ratio: 4.0
